# -*- coding: utf-8 -*-
"""data_prep.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mnRAR3RxZojK4RemHcoJc4hX4DgIaGGk
"""

import pandas as pd

# 1. Load the raw dataset
df = pd.read_csv('owid-co2-data.csv')

# 2. Data Cleaning: Filter for years from 1990 onwards and remove non-country entries
# (Entries without an ISO code are usually regional aggregates like 'World' or 'Africa')
df_clean = df[df['iso_code'].notnull()].copy()
df_clean = df_clean[df_clean['year'] >= 1990]

# 3. Fill missing values with 0 for sectoral columns so we can add them together
sector_cols = ['coal_co2', 'oil_co2', 'gas_co2', 'flaring_co2', 'cement_co2', 'other_industry_co2']
df_clean[sector_cols] = df_clean[sector_cols].fillna(0)

# 4. Create Sector Aggregates (Grouping specific fuels into general sectors)
df_clean['Industry_CO2'] = df_clean['cement_co2'] + df_clean['other_industry_co2']
df_clean['Energy_CO2'] = df_clean['coal_co2'] + df_clean['gas_co2'] + df_clean['flaring_co2']
df_clean['Transport_CO2'] = df_clean['oil_co2']  # Using Oil as the proxy for transport

# 5. Keep only the columns we need for the dashboard
cols_to_keep = ['country', 'year', 'iso_code', 'population', 'gdp', 'co2',
                'Industry_CO2', 'Energy_CO2', 'Transport_CO2',
                'co2_per_capita', 'co2_per_gdp']
df_dashboard = df_clean[cols_to_keep].copy()

# 6. Create "Long Format" data (This makes Tableau Bar Charts much easier)
df_long = pd.melt(df_dashboard,
                  id_vars=['country', 'year', 'iso_code', 'population', 'gdp', 'co2', 'co2_per_capita', 'co2_per_gdp'],
                  value_vars=['Industry_CO2', 'Energy_CO2', 'Transport_CO2'],
                  var_name='Sector', value_name='Sector_Emissions')

# Clean up the Sector names (remove the _CO2 suffix)
df_long['Sector'] = df_long['Sector'].str.replace('_CO2', '')

# 7. Save the prepared files for Tableau
df_dashboard.to_csv('prepared_co2_data_wide.csv', index=False)
df_long.to_csv('prepared_co2_data_long.csv', index=False)

print("Success! Your clean data files are ready for Tableau.")