# -*- coding: utf-8 -*-
"""HR_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qStTvXJ6KnNvzksWMX1A9S1emfookBrc
"""

import pandas as pd

df = pd.read_csv('/content/HR_Dataset.csv')
display(df.head())

df.rename(columns={'Last_Promotion_Years_Ago': 'PromotionLast5Years'}, inplace=True)

# Check shape
print("Shape:", df.shape)

# Check columns
print("\nColumns:\n", df.columns)

# Check data types & null values
df.info()

# Check missing values
df.isnull().sum()

df['Attrition'] = df['Attrition'].map({'Yes': 1, 'No': 0})

df.fillna(df.median(numeric_only=True), inplace=True)

import seaborn as sns
import matplotlib.pyplot as plt
sns.countplot(x='Attrition', data=df)
plt.title("Attrition Distribution")
plt.show()

plt.figure(figsize=(8,5))
sns.countplot(x='Department', hue='Attrition', data=df)
plt.title("Attrition by Department")
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(8,5))
sns.boxplot(x='Attrition', y='Monthly_Income', data=df)
plt.title("Salary vs Attrition")
plt.show()

sns.countplot(x='Job_Satisfaction', hue='Attrition', data=df)
plt.title("Job Satisfaction vs Attrition")
plt.show()

sns.boxplot(x='Attrition', y='PromotionLast5Years', data=df)
plt.title("Promotion Delay vs Attrition")
plt.show()

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in df.select_dtypes(include='object').columns:
    df[col] = le.fit_transform(df[col])

X = df.drop(['Attrition', 'Employee_ID'], axis=1)
y = df['Attrition']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': model.coef_[0]
}).sort_values(by='Importance', ascending=False)

importance

import shap

explainer = shap.Explainer(model, X_train)
shap_values = explainer(X_test)

shap.plots.beeswarm(shap_values)

confusion_matrix(y_test, y_pred)

accuracy_score(y_test, y_pred)